// Generated by ReScript, PLEASE EDIT WITH CARE


var frenchLaw = (require("french-law"));

var resetLog = (function() {
    return frenchLaw.eventsManager.resetLog();
  });

var retrieveRawEventsSerialized = (function() {
    return frenchLaw.eventsManager.retrieveRawEvents();
  });

var retrieveEventsSerialized = (function() {
    return frenchLaw.eventsManager.retrieveEvents();
  });

var computeAllocationsFamiliales = (function(input) {
    frenchLaw.eventsManager.resetLog();
    return AllocationsFamilialesLib.interfaceAllocationsFamiliales(input).iMontantVerse;
  });

var computeAidesAuLogement = (function(input) {
    frenchLaw.eventsManager.resetLog(0);
    return frenchLaw.AidesLogementLib.calculetteAidesAuLogementGardeAlternee(input).aideFinale;
  });

export {
  resetLog ,
  retrieveRawEventsSerialized ,
  retrieveEventsSerialized ,
  frenchLaw ,
  computeAllocationsFamiliales ,
  computeAidesAuLogement ,
}
/* frenchLaw Not a pure module */
